### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by prodigy007** [allure-framework/allure-mstest-adapter#11]
Release no.
Almost managed to build in addition:
<a target="_blank" href="http://radikal.ru/big/c35ff22c40e44ff385ef58598c65a584"><img src="http://s017.radikal.ru/i414/1509/9a/7fe1d66169cc.png" ></a>
I tried to take the old commit, but in the end still falls somewhere in the generation now here::
<a target="_blank" href="http://radikal.ru/big/e1e603a4e9904bf094996b74d8e778bc"><img src="http://s017.radikal.ru/i426/1509/27/efff9e0e0740.png" ></a>

You can make a release?

**Comment by vania-pooh** [comment]
Разработчик не понимает по-русски. Пиши по-английски.
@someuser77 can you please clarify build requirements for this adapter?

**Comment by prodigy007** [comment]
It turns github.com holds in general, all the old branches of projects, try an hour to download something old
https://github.com/allure-framework/allure-mstest-adapter/network

for example
https://github.com/allure-framework/allure-mstest-adapter/tree/a4d44ed67a0dc7da766bac39dae94a3b24b7b855

**Comment by someuser77** [comment]
### For the compile time error: ###
Basically what works for me is:
```
git clone --recursive https://github.com/allure-framework/allure-mstest-adapter.git
```
and then first opening and building allure-mstest-adapter\allure-csharp-commons\AllureCSharpCommons.sln in VS and then allure-mstest-adapter\MSTestAllureAdapter.sln
or:
```
git clone --recursive https://github.com/allure-framework/allure-mstest-adapter.git
cd allure-mstest-adapter
cd allure-csharp-commons
nuget restore AllureCSharpCommons.sln
msbuild AllureCSharpCommons.sln
cd ..
nuget restore MSTestAllureAdapter.sln
msbuild MSTestAllureAdapter.sln
```
assuming you use the VS command prompt and have [nuget.exe](https://dist.nuget.org/index.html) in your path.

Then you can reference the created DLL files.

Let me know if it works or not and if not then what is your scenario.

### For the runtime error: ###
Is it the sample.trx that comes with the solution or is it yours?
If its not the one that's in the repository can you attach/pastebin it?

**Comment by prodigy007** [comment]
Thanks, really works if you download through git.exe

and not just the link of the project through the web site.
I try to generate a report on weekdays.

**Comment by prodigy007** [comment]
Working. THX
Version of the report, as I understand it strictly 1.4.0

**Comment by vania-pooh** [comment]
@prodigy007 no, it's strictly 1.4.x because when we change major version we can also change XML document format. Between minor versions we guarantee the same input XML support.
