### ISSUE TITLE
MSTestAllureAdapter generates output files containing UTF8 BOM

### ISSUE THREAD

**Issue by ThaStealth** [allure-framework/allure-mstest-adapter#12]
It seems the MSTestAllureAdapter sometimes generates files containing the BOM even when the UTF8Encoding is set to not to do this.

This is a sample of an output I got when converting a TRX to a XML file:
ef bb bf 3c 3f 78 6d 6c 20 76 65 72 73 69 6f 6e 3d 22 31 2e 30 22 20 65 6e 63 6f 64 69 6e 67 3d 22 75 74 66 2d 38 22 3f 3e

**Comment by someuser77** [comment]
@ThaStealth thank you very much for submitting this issue.
I think I've tracked down the cause and [created a pull request](https://github.com/allure-framework/allure-csharp-commons/pull/19).
It appeared to resolve the issue when I was testing it but you can apply the change manually and see if it resolves it for you too.
