### ISSUE TITLE
Release needed.

### ISSUE THREAD

**Issue by william-mcdonald** [allure-framework/allure-mstest-adapter#18]
A release would be appreciated. Your project isn't very clear on how it is meant to added to Allure2 and there is no document on how to do this.

**Comment by Bakanych** [comment]
Hi, this repo is actually deprecated. Nevertheless you still can use current version of mstest adapter and feed results to allure 2 cli as it supports both v1 and v2 data formats.

**Comment by Bakanych** [comment]
@william-mcdonald please follow this documentation: https://docs.qameta.io/allure/#_mstest
You also can ask questions in the [gitter chat](https://gitter.im/allure-framework/allure-core).
